### ISSUE TITLE
When typeName is equal to tuple, Unknown type is reported

### ISSUE THREAD

**Issue by tcscat** [rvullriede/evm-abi-decoder#14]
When typeName is equal to tuple, Unknown type is reported

**Comment by tcscat** [comment]
Please help me

**Comment by rvullriede** [comment]
True. The original code was written before solidity introduced tuples and naturally doesn't support them. Since I don't personally don't have a need for this, it's low priority for me.
Maybe you'll be able to provide a PR for this?
